### ISSUE TITLE
For Daniel L.S.

### ISSUE THREAD

**Issue by ida** [ida/BookLook#3]
Hi @ldanielswakman,

in reference to your tweet cited below I started a prototype here, which is by no means finished, but it should work for your requirements at the current state, in case you're interested in a JS-solution, which I'd choose for cross-browser-compatibility.

Demo&Remixlink @ https://book-look.glitch.me/

Cheers, Ida

-----------------------------------------------------------------------------------------
https://twitter.com/ldanielswakman/status/953225103017435136
"CSS Challenge / help wanted! Escalating this to #css & #frontend twitter: I'm looking for a way for a variable block of text to automatically flow to a required number of columns, see image. Column height/width defined, columns should be laid out horizontally. Any ideas?"

**Comment by ldanielswakman** [comment]
Hi @ida!  Thanks a lot for your JS solution to my (still unresolved) CSS problem! Great to have different people around thinking of approaches and solutions. I was looking at your suggestion; it seems to work in the sense of horizontally laying out elements on the page (via `inline-block` and fixed width if I see it correctly?), and distributing the text via JS. However it doesn't adapt well yet when one resizes the page, which is a pity. The thing I enjoy about a CSS-only (or mainly) solution is that it automatically re-flows text in the columns upon resizing.

Actually I've had another reply/solution to my problem which involves mostly CSS and the `column` properties (solving the text flow), and then setting the width of the container via placing an 'end anchor' after the last paragraph, which JS can then detect the position of. See tweet linked below; what do you think?
https://twitter.com/sambhavggore/status/953710392454320134

**Comment by ida** [comment]
Hi @ldanielswakman, thanks for your feedback, appreciate it!

> It seems to work in the sense of horizontally laying out elements on the page via inline-block and fixed width if I see it correctly?

Yupp, exactly. That way it scales well for mobiles, too, btw.

> However it doesn't adapt well yet when one resizes the page, which is a pity.

Was heavily rewriting the script, works currently work with fixed width and height, if you want to have another look. For the other cases I opened #11, thanks fo the hint.

> I've had another reply (...) what do you think?

Looking at https://codepen.io/sambhav/pen/XVxEJJ, I realize I might not have understood your requirements correctly: Column-height and width are altered, I thought you wanted them fixed and all columns have the same width? Sambhav Gore's example differs from that.

He's right though, that it's a pretty tricky task and for larger amounts of text I'd go for serverside pre-processing, rather than putting calculation-weight on the client.

**Comment by ldanielswakman** [comment]
Hi — yes indeed, maybe I have not been sufficiently clear. The key task I want to achieve is that text automatically flows horizontally, starting at the left column (can be fixed width), and filling out towards the right, never wrapping, scrolling if necessary. Any container div should be as wide as the number of columns necessary for the text to be accommodated.

I've opened up a StackOverflow question in a last attempt to find an elegant CSS-only solution: https://stackoverflow.com/questions/48526864/how-to-wrap-nicely-using-css-columns-in-a-horizontal-scrolling-layout

Any further ideas or suggestions are welcome :) — Thanks again for the help so far!

**Comment by ida** [comment]
Good morning @ldanielswakman, thanks for your explanations and good idea, to move this to SO.

As said, I wouldn't go with CSS-only because of no support for IE < 11 and in general more and more users avoid updating their browsers, due to the experience that things can get worse instead of better after an upgrade.

Nevertheless curious to see, if you find a modern solution for the future! Cheers, Ida

**Comment by ldanielswakman** [comment]
Right yeah the IE < 11 compatibility might be an issue; maybe there are graceful fallbacks to use there. Cheers!
